skeleton of connected to devdb endpoint, setting up devdb

diff --git a/start_dev_environment b/start_dev_environment
--- a/start_dev_environment
+++ b/start_dev_environment
@@ -100,5 +100,17 @@ fi
 
 # refresh database if requested
 if [ $REFRESH_DB -eq 1 ]; then
-    echo "Thanks for specifying the database-refresh option! :) This is currently not implemented :( but should be soon!"
+    #echo "Thanks for specifying the database-refresh option! :) This is currently under construction :( hopefully working soon!"
+    curl -O http://astrosky.eco/download/devdb.sql
+    if [ -z "devdb.sql" ]; then
+        echo "ERROR: download of devdb.sql was uncessful"
+        exit 1
+    else
+        if [ "$(docker exec -it "AstroskyDB" psql -U postgres -Atq -c "SELECT COUNT(datname) FROM pg_database WHERE datname = 'devdb'")" -eq 1 ]; then
+            # dev db already exists; potentially need to clean it before running script to repopulate
+        else
+            # dev db does not already exist, needs to be created and set up
+
+        # now we can run the downloaded database file
+        docker exec -it "AstroskyDB" psql -d devdb -f devdb.sql
 fi
